name: Packer Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - name: Zip repository
      run: |
        mkdir -p dist
        git archive --format=zip HEAD -o dist/Express_App-1.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-repo
        path: dist/Express_App-1.zip

    - name: Packer Init
      run: packer init .


    - name: Configure AWS Credentials and build packer
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: "AKIA5XTV4KA7MH3V7SQI"
          aws-secret-access-key: "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"
          aws-region: 'us-east-1'
          
    - name: Packer Build
      run: |
        packer build .

    - name: Configuring Demo AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: "AKIA5XTV4KA7MH3V7SQI" 
          aws-secret-access-key: "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"
          aws-region: 'us-east-1'

    - name: Update launch template and refresh auto scaling group
      run: |
            ami_ID=$(aws ec2 describe-images --filters "Name=name,Values=amazon-linux-2-node-mysql-*" "Name=owner-id,Values=944066285630" --query "reverse(sort_by(Images, &CreationDate))[0].ImageId")
            echo $ami_ID
            template_ID=$(aws ec2 describe-launch-templates --launch-template-name asg_launch_config | jq '.LaunchTemplates[].LaunchTemplateId')
            echo $template_ID
            aws ec2 create-launch-template-version --launch-template-name asg_launch_config --version-description WebVersion2 --source-version 1 --launch-template-data "ImageId=$ami_ID"
            aws autoscaling update-auto-scaling-group --auto-scaling-group-name csye6225-asg-spring2023 --launch-template LaunchTemplateId=$template_ID,Version='$Latest'
            aws autoscaling start-instance-refresh --auto-scaling-group-name csye6225-asg-spring2023

    - name: Clean up
      run: |
        rm -r dist

